blinklabs-io/cdnsd

- internal/config/config.go
- internal/indexer/indexer.go
> feat: switch to new datum format

- internal/dns/dns.go
- internal/indexer/indexer.go
> feat: root server DNS behavior

- internal/config/config.go
- internal/dns/dns.go
> feat: DNS fallback server support

- internal/config/config.go
- internal/dns/dns.go
> feat: query logging

- internal/dns/dns.go
> feat: explicitly query fallback servers for NS records

- internal/dns/dns.go
> feat: rework recursion support

- scripts/create-test-data/README.md
- scripts/create-test-data/create-test-data
- scripts/create-test-data/main.ts
> feat: script for creating test domain data

- scripts/create-test-data/main.ts
> fix: update datum format to include nameserver

- cmd/cdnsd/main.go
- internal/config/config.go
- internal/dns/dns.go
- internal/indexer/indexer.go
- internal/logging/logging.go
- internal/state/state.go
Use
```
golines -w --ignore-generated --chain-split-dots --max-len=80 --reformat-tags .
```
> chore: run golines

- internal/dns/dns.go
- internal/state/state.go
> feat: answer direct queries for nameservers

- scripts/create-test-data/main.ts
> feat: update test data script for new datum format

- scripts/create-test-data/main.ts
> feat: add --nameserver as shortcut in test data script

- internal/state/state.go
> feat: delete old records on domain update

- internal/dns/dns.go
- internal/indexer/indexer.go
- internal/state/state.go
> feat: refactor storage

- internal/dns/dns.go
- internal/state/state.go
This commit does the following:
* support lookup of more than NS from local storage
* add convenience function for converting from our storage format to dns.RR
* remove NS lookup logic for fallback servers and pass along query verbatim if not in local storage
* remove (now) unneeded state helper function
Fixes #107 and #159
> feat: refactor lookup logic

- Makefile
- cmd/cdnsd/main.go
- internal/version/version.go
> feat: log version at startup

- internal/indexer/indexer.go
> feat: periodic log message during catch-up sync

- internal/config/config.go
- internal/config/profile.go
- internal/indexer/indexer.go
> feat: support for multiple TLDs

- internal/dns/dns.go
This adds support for falling back to a matching CNAME record when there's no available A/AAAA record matching a query.
Fixes #186
> feat: support for CNAME record fallback

- internal/handshake/block.go
- internal/handshake/block_test.go
- internal/handshake/transaction.go
This adds support for decoding Handshake blocks and transactions, including inputs, outputs, and witnesses.
Fixes #256
> feat: support for decoding Handshake block data

- internal/handshake/block_test.go
- internal/handshake/covenant.go
- internal/handshake/covenant_test.go
- internal/handshake/domain.go
- internal/handshake/domain_test.go
- internal/handshake/transaction.go
This adds support for parsing generic covenant data into specific covenant types. It also adds support for parsing the domain resource data included with the Update and Register covenant types
Fixes #258
> feat: support for decoding Handshake domain record data
